name: rickandmortyapp
description: "the app that uses api rick and morty"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  dio: ^5.9.0
  hive_flutter: ^1.1.0
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/app-icon.png"
